name: Test env
inputs:
  var1:
    description: Tag for packages
  var2:
    description: Space separated package names
runs:
  using: composite
  steps:
  - shell: python
    run: |
      import dotenv, json
      inputs=json.loads('${{ toJSON(inputs) }}')
  - shell: bash
    run: env | sort
