name: Build common deps

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        qt-version: [ 5, 6 ]
        name: [ "windows-msvc", "windows-mingw", "linux", "macos-arm64", "macos-x86_64" ]
        include:
          - name: "windows-msvc"
            os: "windows-latest"
          - name: "windows-mingw"
            os: "windows-latest"
          - name: "linux"
            os: "ubuntu-latest"
          - name: "macos-arm64"
            os: "macos-14"
          - name: "macos-x86_64"
            os: "macos-13"

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: ${{ matrix.profile.name }}-qt${{ matrix.qt-version }}
      shell: bash
      run: |
        mkdir -p $RUNNER_WORKSPACE/artifacts/
        echo '${{ toJSON(matrix) }}' > $RUNNER_WORKSPACE/artifacts/matrix.json
    - uses: actions/upload-artifact@v4
      with:
        name: "matrix-info"
        path: "${{ runner.workspace }}/artifacts"
  all:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - run: |
          echo