name: Build common deps

on:
  push:
    branches: []
  workflow_dispatch:
    inputs:
      publish-www:
        description: 'Publish on WWW'
        required: false
        type: boolean
      build-type:
        description: 'Build type'
        required: false
        type: string
      BUILD_TYPE:
        type: environment
        
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  PROJECT_NAME: test
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        name: [ "windows-msvc", "windows-mingw", "linux", "macos-arm64", "macos-x86_64" ]
        include:
          - name: "windows-msvc"
            os: "windows-latest"
            msystem: "MSYS"
          - name: "windows-mingw"
            os: "windows-latest"
            msystem: "UCRT64"
          - name: "linux"
            os: "ubuntu-latest"
          - name: "macos-arm64"
            os: "macos-14"
          - name: "macos-x86_64"
            os: "macos-13"

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps: 
    - name: Setup bashenv
      run: |
        BASH_ENV="$(cd $RUNNER_TEMP; pwd)/.bashrc"
        touch $BASH_ENV
        echo BASH_ENV="$BASH_ENV" >> $GITHUB_ENV
        if [[ $RUNNER_OS == "Windows" ]]; then
          echo "export PATH=\"/c/msys64/usr/bin:$PATH\"" >> $BASH_ENV
          echo "export MSYSTEM=${{ matrix.msystem }}" >> $BASH_ENV
          echo "source /c/msys64/etc/msystem" >> $BASH_ENV
        fi
    - name: uname
      run: |
        echo UNAME_S=$(uname -s)
        echo UNAME_M=$(uname -m)
        echo UNAME_O=$(uname -o)
    - run: (env | grep -e '^MSYSTEM' -e '^MINGW' -e '^PATH' ) || echo "no msystem found"
    - name: Checkout repository
      uses: actions/checkout@v4
        
#    - name: Uploading
#      uses: actions/upload-artifact@v4
#      with:
#        name: "${{ env.FULL_NAME }}"
#        path: "${{ runner.workspace }}/out/*"
