name: Build common deps

on:
  workflow_dispatch

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  PROJECT_NAME: test
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        qt-version: [ 5, 6 ]
        name: [ "windows-msvc", "windows-mingw", "linux", "macos-arm64", "macos-x86_64" ]
        include:
          - name: "windows-msvc"
            os: "windows-latest"
          - name: "windows-mingw"
            os: "windows-latest"
          - name: "linux"
            os: "ubuntu-latest"
          - name: "macos-arm64"
            os: "macos-14"
          - name: "macos-x86_64"
            os: "macos-13"

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - shell: bash
      run: |
        export FULL_NAME=${{ env.PROJECT_NAME }}-${{ matrix.name }}-qt${{ matrix.qt-version }}
        mkdir -p $RUNNER_WORKSPACE/artifacts/
        echo ARTIFACTS_DIR=$RUNNER_WORKSPACE/artifacts/ >> $GITHUB_ENV
        echo FULL_NAME=$FULL_NAME >> $GITHUB_ENV
    - run: |
        echo "::notice::Save to $ARTIFACTS_DIR"
        env | sort
        echo '${{ toJSON(env) }}' >> $ARTIFACTS_DIR/env.json
        echo '${{ toJSON(github) }}' >> $ARTIFACTS_DIR/github.json
        echo '${{ toJSON(runner) }}' >> $ARTIFACTS_DIR/runner.json
    - name: Uploading ${{ env.FULL_NAME }}
      uses: actions/upload-artifact@v4
      with:
        name: "temp-${{ env.FULL_NAME }}"
        path: "${{ env.ARTIFACTS_DIR }}/*"
  sign-macos-packages:
    needs: build
    runs-on: macos-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ${{ runner.workspace }}/artifacts
      - uses: geekyeggo/delete-artifact@v5
        with:
          name: temp*-macos-*
      - run: |
          cd $RUNNER_WORKSPACE/artifacts
          for i in *;
          do
            mv -v $i ${i#temp-*}
          done
      - name: Upload signed artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "macos-artifacts"
          path: ${{ runner.workspace }}/artifacts

  all:
    needs: [ build, sign-macos-packages ]
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ${{ runner.workspace }}/artifacts
      - uses: geekyeggo/delete-artifact@v5
        with:
          name: temp-*
      - run: |
          cd $RUNNER_WORKSPACE/artifacts
          for i in *;
          do
            mv -v $i ${i#temp-*}
          done
      - name: Uploading all
        uses: actions/upload-artifact@v4
        with:
          name: "common-artifacts"
          path: ${{ runner.workspace }}/artifacts
          
