name: Build common deps

on:
  push:
    branches: []
  workflow_dispatch:
    inputs:
      publish-www:
        description: 'Publish on WWW'
        required: false
        type: boolean
      build-type:
        description: 'Build type'
        required: false
        type: string
      BUILD_TYPE:
        type: environment
        
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  PROJECT_NAME: test
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        name: [ "windows-msvc", "windows-mingw", "macos-arm64", "macos-x86_64", "linux-x86_64", "linux-arm" ]
        include:
          - name: "windows-msvc"
            os: "windows-latest"
            msystem: "MSYS"
          - name: "windows-mingw"
            os: "windows-latest"
            msystem: "UCRT64"
          - name: "macos-arm64"
            os: "macos-15"
          - name: "macos-x86_64"
            os: "macos-15-intel"
          - name: "linux-x86_64"
            os: "ubuntu-latest"
          - name: "linux-arm"
            os: "ubuntu-24.04-arm"

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps: 
    - name: setup bashenv
      run: |
        BASH_ENV=$(cd $RUNNER_WORKSPACE; pwd)/.bashrc
        touch $BASH_ENV
        echo "BASH_ENV=$BASH_ENV" >> $GITHUB_ENV
        
    - name: setup profile variables
      env:
        PROFILE_NAME: ${{ matrix.name }}
        MSYSTEM: ${{ matrix.msystem }}
        BASH_ENV: '${{runner.workspace}}/.bashrc'
      shell: python
      run: |
        import os
        _env=f'''
        export PROFILE_NAME={os.environ.get("PROFILE_NAME", "default")}
        export MSYSTEM={os.environ.get("MSYSTEM", "")}
        if [[ -n $MSYSTEM ]]; then
          export MSYS2_PATH_TYPE=inherit
          export CHERE_INVOKING=1
          source /c/msys64/etc/profile
        fi
        '''
        print(_env)
        with open(os.environ.get("BASH_ENV"), "a") as gh_env:
          gh_env.write(_env)
    
    - name: Test variables
      shell: bash --norc --noprofile {0}
      env:
        MSYSTEM: ${{ matrix.msystem }}
      run: |
        echo MSYSTEM=$MSYSTEM
    - name: Get host infos
      run: |
        echo "OSTYPE=$OSTYPE"
        echo "MACHTYPE=$MACHTYPE"
        echo "HOSTTYPE=$HOSTTYPE"
    - name: uname
      run: |
        echo UNAME_S=$(uname -s)
        echo UNAME_M=$(uname -m)
        echo UNAME_O=$(uname -o)
#    - uses: donarturo11/testWorkflow/.github/actions/test-env@main
#      with:
#        var1: 'val1'
#        var2: 'val2'
    - name: clang dump machine
      run: which clang; clang -dumpmachine
    - run: (env | grep -e '^MSYSTEM' -e '^MINGW' -e '^PATH' ) || echo "no msystem found"
    - name: Checkout repository
      uses: actions/checkout@v4
        
#    - name: Uploading
#      uses: actions/upload-artifact@v4
#      with:
#        name: "${{ env.FULL_NAME }}"
#        path: "${{ runner.workspace }}/out/*"
